# Generated by Django 3.1 on 2020-08-14 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=120, unique=True, verbose_name='event_name')),
                ('event_category', models.CharField(max_length=120, verbose_name='event_category')),
                ('thumbnail', models.CharField(max_length=120, verbose_name='thumbnail')),
                ('event_place', models.CharField(max_length=120, verbose_name='event_place')),
                ('event_address', models.CharField(max_length=120, verbose_name='event_address')),
                ('event_initial_date', models.CharField(max_length=120, verbose_name='event_initial_date')),
                ('event_final_date', models.CharField(max_length=120, verbose_name='event_final_date')),
                ('event_type', models.CharField(max_length=120, verbose_name='event_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
